shapes: main.o shape.o menu.o
	g++ -std=c++20 -o shapes.out main.o shape.o menu.o

main.o: main.cpp
	g++ -std=c++20 -c main.cpp

shape.o: shape.cpp
	g++ -std=c++20 -c shape.cpp

menu.o: menu.cpp
	g++ -std=c++20 -c menu.cpp