delete from Game;
delete from Console;/*
delete from Company;

insert into Company values
('505 Games'),
('Absolute Entertainment'),
('Activision'),
('Aicom'),
('A.I. Company Ltd.'),
('Aksys Games'),
('Ancient'),
('Arc System Works'),
('ASCII'),
('Atlus'),
('Bandai'),
('Beam Software'),
('BlueSky Software'),
('Brøderbund'),
('Bullet Proof Software'),
('Capcom'),
('Camelot Software'),
('Chunsoft'),
('Climax Entertainment'),
('Compile'),
('Crea-Tech'),
('Culture Brain'),
('D4 Enterprise'),
('Data East'),
('dB-SOFT'),
('Dual Corporation'),
('Electro Brain'),
('Electronic Arts'),
('Enterbrain'),
('Factor 5'),
('FCI'),
('G-Mode'),
('Game Freak'),
('HAL Laboratory'),
('Hamster'),
('Hect'),
('Hudson Soft'),
('Human Entertainment'),
('Iguana Entertainment'),
('Imagineering'),
('Intelligent Systems'),
('Interplay'),
('Irem'),
('ISCO'),
('Jaleco'),
('Johnson Voorsanger Productions'),
('Kemco'),
('KID'),
('Koei'),
('Konami'),
('LucasArts'),
('Majesco Entertainment'),
('Make Software'),
('Micronics'),
('Midway Games'),
('MNM Software'),
('Namco'),
('Natsume'),
('Naxat Soft'),
('NCS Corp'),
('NetFarm'),
('Nihon Bussan'),
('Nihon Falcom'),
('Nintendo'),
('Nippon Computer Systems'),
('Novotrade Interactive'),
('Now Production'),
('Pack-In-Video'),
('Paon'),
('Pax Softnica'),
('Polygames'),
('Produce!'),
('Quest'),
('Quintet'),
('Rare'),
('Sammy'),
('Sandcastle'),
('SAS Sakata'),
('Sculptured Software'),
('SEGA'),
('Shinsei'),
('Shiny Entertainment'),
('SNK'),
('Square'),
('Sunsoft'),
('T&E Soft'),
('Taito'),
('Takara'),
('Tamtex'),
('Technōs Japan'),
('Tecmo'),
('Tokai Engineering'),
('Tomy'),
('TOSE'),
('Toshiba EMI'),
('Tozai'),
('Traveller''s Tales'),
('Treasure'),
('Ubisoft'),
('Ultra Games'),
('UPL'),
('Westone'),
('Workss');*/

insert into console values
('NES', 'Nintendo Entertainment System', 'Nintendo'),
('SNES', 'Super Nintendo Entertainment System', 'Nintendo'),
('N64', 'Nintendo 64', 'Nintendo'),
('SGEN', 'SEGA Genesis', 'SEGA'),
('GB', 'Game Boy', 'Nintendo'),
('GBC', 'Game Boy Color', 'Nintendo'),
('GBA', 'Game Boy Advance', 'Nintendo');