delete from Game where console = 'SNES';
insert into Game values
('SNES000','F-Zero','F-Zero','F-Zero',1991,1992,1990,array['Nintendo'],'Nintendo','SNES'),
('SNES001','SimCity','SimCity','SimCity',1991,1992,1991,array['Nintendo'],'Nintendo','SNES'),
('SNES002','Super Castlevania IV','Super Castlevania IV','Akumajō Dracula',1991,1992,1991,array['Konami'],'Konami','SNES'),
('SNES003','Street Fighter II: The World Warrior','Street Fighter II: The World Warrior','Street Fighter II: The World Warrior',1992,1992,1992,array['Capcom'],'Capcom','SNES'),
('SNES004','Super Mario World','Super Mario World','Super Mario World',1991,1992,1990,array['Nintendo'],'Nintendo','SNES'),
('SNES005','The Legend of Zelda: A Link to the Past','The Legend of Zelda: A Link to the Past','Zelda no Densetsu: Kamigami no Triforce',1992,1991,1992,array['Nintendo'],'Nintendo','SNES'),
('SNES006','Donkey Kong Country','Donkey Kong Country','Super Donkey Kong',1994,1994,1994,array['Rare'],'Nintendo','SNES'),
('SNES007','Mario''s Super Picross','Mario''s Super Picross','Mario no Super Picross',null,null,1995,array['Ape','Jupiter'],'Nintendo','SNES'),
('SNES008','Fire Emblem: Mystery of the Emblem',null,'Fire Emblem: Monshō no Nazo',null,null,null,array['Intelligent Systems'],'Nintendo','SNES'),
('SNES009','R-Type III: The Third Lightning','R-Type III: The Third Lightning','R-Type III: The Third Lightning',null,null,null,array['Tamtex'],'Jaleco','SNES'),
('SNES010','Contra III: The Alien Wars','Super Probotector: Alien Rebels','Contra Spirits',null,null,null,array[''],'','SNES'),
('SNES011','Fire Emblem: Genealogy of the Holy War',null,'Fire Emblem: Seisen no Keifu',null,null,null,array['Intelligent Systems'],'Nintendo','SNES'),
('SNES012','Banshee''s Last Cry',null,'Kamaitachi no Yoru',null,null,null,array['Chunsoft'],'Chunsoft','SNES'),
('SNES013',null,null,'Shin Megami Tensei',null,null,null,array[''],'','SNES'),
('SNES014','Super Ghouls ''n Ghosts','Super Ghouls ''n Ghosts','Chou Makaimura',null,null,null,array[''],'','SNES'),
('SNES015','Romance of the Three Kingdoms IV: Wall of Fire','','Sangokushi IV',null,null,null,array[''],'','SNES'),
('SNES016','The Legend of the Mystical Ninja','','Ganbare Goemon: Yukihime Kyūshutsu Emaki',null,null,null,array[''],'','SNES'),
('SNES017','ActRaiser',null,'ActRaiser',null,null,null,array[''],'','SNES'),
('SNES018',null,null,'Heracles no Eikō III: Kamigami no Chinmoku',null,null,null,array[''],'','SNES'),
('SNES019','Final Fight','Final Fight','Final Fight',null,null,null,array[''],'','SNES'),
('SNES020','Gradius III','','',null,null,null,array[''],'','SNES'),
('SNES021','Kirby''s Dream Course','Kirby''s Dream Course','Kirby Bowl',null,null,null,array[''],'','SNES'),
('SNES022','Donkey Kong Country 2: Diddy''s Kong Quest','Donkey Kong Country 2: Diddy''s Kong Quest','Super Donkey Kong 2: Dixie & Diddy',null,null,null,array[''],'','SNES'),
('SNES023',null,null,'Magical Drop',null,null,null,array[''],'','SNES'),
('SNES024','Street Fighter II'' Turbo: Hyper Fighting','Street Fighter II'' Turbo: Hyper Fighting','Street Fighter II Turbo: Hyper Fighting',null,null,null,array[''],'','SNES'),
('SNES025','Breath of Fire II','Breath of Fire II','Breath of Fire II: Shimei no Ko',null,null,null,array[''],'','SNES'),
('SNES026',null,null,'Famicom Bunko: Hajimari no Mori',null,null,null,array[''],'','SNES'),
('SNES027',null,null,'Fushigi no Dungeon 2: Fūrai no Shiren',null,null,null,array[''],'','SNES'),
('SNES028','Kirby''s Avalanche','Kirby''s Ghost Trap',null,null,null,null,array[''],'','SNES'),
('SNES029','Super Metroid','Super Metroid','Super Metroid',null,null,null,array[''],'','SNES'),
('SNES030',null,null,'Otogirisō',null,null,null,array[''],'','SNES'),
('SNES031','Cybernator','Cybernator','Jūsō Kihei Valken',null,null,null,array[''],'','SNES'),
('SNES032','Vegas Stakes','Vegas Stakes','',null,null,null,array[''],'','SNES'),
('SNES033','Axelay','Axelay','Axelay',null,null,null,array[''],'','SNES'),
('SNES034','Metal Marines','Metal Marines','Militia',null,null,null,array['Namco'],'Namco','SNES'),
('SNES035',null,null,'Panel de Pon',null,null,null,array[''],'','SNES'),
('SNES036','Super Street Fighter II: The New Challengers','Super Street Fighter II: The New Challengers','Super Street Fighter II: The New Challengers',null,null,null,array[''],'','SNES'),
('SNES037','Donkey Kong Country 3: Dixie Kong''s Double Trouble!','Donkey Kong Country 3: Dixie Kong''s Double Trouble!','Super Donkey Kong 3: Nazo no Krems Shima',null,null,null,array[''],'','SNES'),
('SNES038',null,null,'Treasure Hunter G',null,null,null,array[''],'','SNES'),
('SNES039','Harvest Moon','Harvest Moon','',null,null,null,array[''],'Natsume','SNES'),
('SNES040','Pac-Attack','','',null,null,null,array[''],'','SNES'),
('SNES041',null,null,'Super R-Type',null,null,null,array[''],'','SNES'),
('SNES042',null,null,'Cosmo Gang the Puzzle',null,null,null,array[''],'','SNES'),
('SNES043','DoReMi Fantasy: Milon''s DokiDoki Adventure','','DoReMi Fantasy: Milon no Dokidoki Daibouken',null,null,null,array[''],'','SNES'),
('SNES044','Super Turrican','Super Turrican','',null,null,null,array[''],'','SNES'),
('SNES045',null,null,'Super Gussun Oyoyo',null,null,null,array[''],'','SNES'),
('SNES046',null,null,'Heracles no Eikō IV: Kamigami kara no Okurimono',null,null,null,array[''],'','SNES'),
('SNES047',null,null,'Famicom Tantei Club Part II: Ushiro ni Tatsu Shōjo',null,null,null,array[''],'','SNES'),
('SNES048',null,null,'Front Mission Series: Gun Hazard',null,null,null,array[''],'','SNES'),
('SNES049',null,null,'Ganbare Goemon 2: Kiteretsu Shōgun Magginesu',null,null,null,array[''],'','SNES'),
('SNES050','Super Mario RPG: Legend of the Seven Stars','Super Mario RPG: Legend of the Seven Stars','Super Mario RPG',null,null,null,array['Square'],'Nintendo','SNES'),
('SNES051',null,null,'Fire Emblem: Thracia 776',null,null,null,array[''],'','SNES'),
('SNES052',null,null,'Gakkou de atta Kowai Hanashi',null,null,null,array[''],'','SNES'),
('SNES053','Secret of Mana','Secret of Mana','Seiken Densetsu 2',null,null,null,array[''],'','SNES'),
('SNES054','Space Invaders: The Original Game','Space Invaders: The Original Game','Space Invaders: The Original Game',null,null,null,array[''],'','SNES'),
('SNES055','Super Turrican 2','','',null,null,null,array[''],'','SNES'),
('SNES056','Ogre Battle: The March of the Black Queen',null,'Densetsu no Ogre Battle',null,null,null,array[''],'','SNES'),
('SNES057','Nobunaga''s Ambition','','Super Nobunaga no Yabou Zenkokuban',null,null,null,array[''],'','SNES'),
('SNES058','Kirby''s Dream Land 3','Kirby''s Dream Land 3','Hoshi no Kirby 3',null,null,null,array[''],'','SNES'),
('SNES059',null,null,'Tactics Ogre: Let Us Cling Together',null,null,null,array[''],'','SNES'),
('SNES060','Uncharted Waters: New Horizons','','Daikōkai Jidai II',null,null,null,array[''],'','SNES'),
('SNES061','Super Punch-Out!!','Super Punch-Out!!','Super Punch-Out!!',null,null,null,array[''],'','SNES'),
('SNES062',null,null,'Der Langrisser',null,null,null,array[''],'','SNES'),
('SNES063',null,null,'Super Wagan Land',null,null,null,array[''],'','SNES'),
('SNES064','Genghis Khan II: Clan of the Gray Wolf','','Super Aoki Ōkami to Shiroki Mejika: Genchou Hishi',null,null,null,array[''],'','SNES'),
('SNES065','Super Mario Kart','Super Mario Kart','Super Mario Kart',null,null,null,array[''],'','SNES'),
('SNES066','Final Fantasy II','Final Fantasy II','Final Fantasy IV',null,null,null,array[''],'','SNES'),
('SNES067','Super Star Wars','Super Star Wars','',null,null,null,array['Sculptured Software','LucasArts'],'LucasArts','SNES'),
('SNES068','Pilotwings','Pilotwings','Pilotwings',null,null,null,array[''],'','SNES'),
('SNES069','Super Star Wars: The Empire Strikes Back','Super Star Wars: The Empire Strikes Back','',null,null,null,array['Sculptured Software','LucasArts'],'LucasArts','SNES'),
('SNES070',null,null,'Taikou Risshiden',null,null,null,array[''],'','SNES'),
('SNES071','Super Star Wars: Return of the Jedi','','',null,null,null,array['Sculptured Software','LucasArts'],'LucasArts','SNES'),
('SNES072',null,null,'Ganbare Goemon 3: Shishijūrokubē no Karakuri Manji Gatame',null,null,null,array[''],'','SNES'),
('SNES073',null,null,'Bahamut Lagoon',null,null,null,array[''],'','SNES'),
('SNES074','Final Fight 2','Final Fight 2','',null,null,null,array[''],'','SNES'),
('SNES075','Kirby Super Star','Kirby''s Fun Pak','Hoshi no Kirby Super Deluxe',null,null,null,array[''],'','SNES'),
('SNES076','Zombies Ate My Neighbors','Zombies','',null,null,null,array[''],'LucasArts','SNES'),
('SNES077','Indiana Jones'' Greatest Adventures','','',null,null,null,array[''],'','SNES'),
('SNES078',null,null,'Romancing SaGa',null,null,null,array[''],'','SNES'),
('SNES079','The Combatribes','','',null,null,null,array[''],'','SNES'),
('SNES080','Street Fighter Alpha 2','','Street Fighter Zero 2',null,null,null,array[''],'','SNES'),
('SNES081','Final Fight 3','Final Fight 3','Final Fight Tough',null,null,null,array[''],'','SNES'),
('SNES082','Kirby''s Star Stacker','','Kirby no Kirakira Kids',null,null,null,array[''],'','SNES'),
('SNES083','Ghoul Patrol','Ghoul Patrol','',null,null,null,array[''],'LucasArts','SNES'),
('SNES084',null,null,'Super Famicom Wars',null,null,null,array[''],'','SNES'),
('SNES085',null,null,'Sutte Hakkun',null,null,null,array[''],'Nintendo','SNES'),
('SNES086',null,null,'Romancing SaGa 2',null,null,null,array[''],'','SNES'),
('SNES087',null,null,'Darius Twin',null,null,null,array[''],'','SNES'),
('SNES088',null,null,'Heisei Shin Onigashima (Zenpen)',null,null,null,array[''],'','SNES'),
('SNES089','Wild Guns','Wild Guns','Wild Guns',null,null,null,array[''],'','SNES'),
('SNES090',null,null,'Heisei Shin Onigashima (Kouhen)',null,null,null,array[''],'','SNES'),
('SNES091',null,null,'Metal Max 2',null,null,null,array[''],'','SNES'),
('SNES092','Aero the Acro-Bat','Aero the Acro-Bat','',null,null,null,array[''],'','SNES'),
('SNES093',null,null,'Clock Tower',null,null,null,array[''],'','SNES'),
('SNES094','Aero the Acro-Bat 2','Aero the Acro-Bat 2','',null,null,null,array[''],'','SNES'),
('SNES095',null,null,'Shin Megami Tensei II',null,null,null,array[''],'','SNES'),
('SNES096',null,null,'Romancing SaGa 3',null,null,null,array[''],'','SNES'),
('SNES097','Final Fantasy Mystic Quest','Mystic Quest Legend','Final Fantasy USA: Mystic Quest',null,null,null,array[''],'','SNES'),
('SNES098','Rival Turf!','Rival Turf!','Rushing Beat',null,null,null,array[''],'','SNES'),
('SNES099',null,null,'Albert Odyssey',null,null,null,array[''],'','SNES'),
('SNES100','Super E.D.F.: Earth Defense Force','Super E.D.F.: Earth Defense Force','Super E.D.F.: Earth Defense Force',null,null,null,array[''],'','SNES'),
('SNES101','Super Bonk','','Chō Genjin',null,null,null,array[''],'','SNES'),
('SNES102',null,null,'Bishōjo Janshi Suchie-Pai',null,null,null,array[''],'','SNES'),
('SNES103',null,null,'Final Fantasy V',null,null,null,array[''],'','SNES'),
('SNES104',null,null,'Shin Megami Tensei if...',null,null,null,array[''],'','SNES'),
('SNES105','Natsume Championship Wrestling','Natsume Championship Wrestling','',null,null,null,array[''],'','SNES'),
('SNES106','The Ignition Factor','The Ignition Factor','Fire Fighting',null,null,null,array[''],'','SNES'),
('SNES107','Final Fantasy III','Final Fantasy III','Final Fantasy VI',null,null,null,array[''],'','SNES'),
('SNES108','Brawl Brothers','Brawl Brothers','Rushing Beat Ran: Fukusei Toshi',null,null,null,array[''],'','SNES'),
('SNES109','Mega Man X','Mega Man X','Rockman X',null,null,null,array[''],'','SNES'),
('SNES110','Chrono Trigger','Chrono Trigger','Chrono Trigger',null,null,null,array[''],'','SNES'),
('SNES111','Super Adventure Island','Super Adventure Island','Takahashi Meijin no Daibōken Jima',null,null,null,array[''],'','SNES'),
('SNES112',null,null,'Rudra no Hihō',null,null,null,array[''],'','SNES'),
('SNES113','Super Adventure Island II','Super Adventure Island II','Takahashi Meijin no Daibōken Jima II',null,null,null,array[''],'','SNES'),
('SNES114',null,null,'Majin Tensei',null,null,null,array[''],'','SNES'),
('SNES115','Power Instinct','','Gōketsuji Ichizoku',null,null,null,array[''],'','SNES'),
('SNES116',null,null,'Metal Max Returns',null,null,null,array[''],'','SNES'),
('SNES117',null,null,'Majin Tensei II: Spiral Nemesis',null,null,null,array[''],'','SNES'),
('SNES118','Mega Man X2','Mega Man X2','Rockman X2',null,null,null,array[''],'','SNES'),
('SNES119','Prince of Persia','Prince of Persia','Prince of Persia',null,null,null,array[''],'','SNES'),
('SNES120',null,null,'Kunio-kun no Dodgeball da yo Zenin Shūgō!',null,null,null,array[''],'','SNES'),
('SNES121',null,null,'Kai: Tsukikomori',null,null,null,array[''],'','SNES'),
('SNES122',null,null,'Kyūyaku Megami Tensei: Megami Tensei I • II',null,null,null,array[''],'','SNES'),
('SNES123','EarthBound','EarthBound','Mother 2: Gyiyg no Gyakushū',null,null,null,array['Ape','HAL Laaboratory'],'Nintendo','SNES'),
('SNES124','Mega Man 7','','Rockman 7: Shukumei no Taiketsu!',null,null,null,array[''],'','SNES'),
('SNES125','Mega Man X3','Mega Man X3','Rockman X3',null,null,null,array[''],'','SNES'),
('SNES126','Breath of Fire','','Breath of Fire: Ryū no Senshi',null,null,null,array[''],'','SNES'),
('SNES127',null,null,'Live A Live',null,null,null,array[''],'','SNES'),
('SNES128',null,null,'Pop''n TwinBee',null,null,null,array[''],'','SNES'),
('SNES129','Demon''s Crest','Demon''s Crest','Demon''s Blazon: Makaimura Monshō-hen',null,null,null,array[''],'','SNES'),
('SNES130','Castlevania Dracula X','Castlevania Dracula X','Akumajō Dracula XX',null,null,null,array[''],'','SNES'),
('SNES131',null,null,'Marvelous Mōhitotsu no Takarajima',null,null,null,array[''],'','SNES'),
('SNES132',null,'Pop''n TwinBee: Rainbow Bell Adventures','TwinBee: Rainbow Bell Adventure',null,null,null,array[''],'','SNES'),
('SNES133','Super Ninja Boy','','Super Chinese World',null,null,null,array[''],'','SNES'),
('SNES134',null,null,'Last Bible III',null,null,null,array[''],'Atlus','SNES'),
('SNES135','Pac-Man 2: The New Adventures','Pac-Man 2: The New Adventures','',null,null,null,array[''],'','SNES'),
('SNES136',null,null,'Metal Slader Glory: Director''s Cut',null,null,null,array[''],'Nintendo','SNES'),
('SNES137','Wrecking Crew ''98','','Wrecking Crew ''98',null,null,null,array[''],'','SNES'),
('SNES138','Star Fox','Starwing','Star Fox',null,null,null,array[''],'','SNES'),
('SNES139','Star Fox 2','','Star Fox 2',null,null,null,array[''],'','SNES'),
('SNES140','Super Soccer','','',null,null,null,array[''],'','SNES'),
('SNES141','Super Mario World 2: Yoshi''s Island','Super Mario World 2: Yoshi''s Island','Super Mario: Yoshi Island',null,null,null,array[''],'','SNES'),
('SNES142','Joe & Mac 2: Lost in the Tropics','Joe & Mac 3: Lost in the Tropics','Tatakae Genshinjin 3: Shuyaku wa Yappari Joe to Mac',null,null,null,array['Data East'],'','SNES'),
('SNES143','Smash Tennis','','',null,null,null,array[''],'','SNES'),
('SNES144','Stunt Race FX','','',null,null,null,array[''],'','SNES'),
('SNES145',null,null,'Super Puyo Puyo 2',null,null,null,array[''],'','SNES'),
('SNES146','Super Tennis','','',null,null,null,array[''],'','SNES'),
('SNES147','Operation Logic Bomb','','',null,null,null,array[''],'','SNES'),
('SNES148','Super Mario All-Stars','Super Mario All-Stars','Super Mario Collection',null,null,null,array[''],'','SNES'),
('SNES149','The Peace Keepers','','',null,null,null,array[''],'','SNES'),
('SNES150',null,null,'Sugoi Hebereke',null,null,null,array[''],'','SNES'),
('SNES151','Super Valis IV','','',null,null,null,array[''],'','SNES'),
('SNES152','Tuff E Nuff','','',null,null,null,array[''],'','SNES'),
('SNES153','Doomsday Warrior','','',null,null,null,array[''],'','SNES'),
('SNES154','Prehistorik Man','','',null,null,null,array[''],'','SNES'),
('SNES155','Psycho Dream','','',null,null,null,array[''],'','SNES'),
('SNES156','Joe & Mac','','Joe & Mac: Tatakae Genshijin',null,null,null,array[''],'','SNES'),
('SNES157',null,null,'Magical Drop II',null,null,null,array[''],'','SNES'),
('SNES158','Spanky''s Quest','','',null,null,null,array[''],'','SNES'),
('SNES159','Super Baseball Simulator 1.000',null,'Super Ultra Baseball',null,null,null,array[''],'','SNES'),
('SNES160','Ka-Blooey','Bombuzal','',null,null,null,array[''],'','SNES'),
('SNES161','Claymates','','',null,null,null,array[''],'','SNES'),
('SNES162','Jelly Boy','','',null,null,null,array[''],'','SNES'),
('SNES163','Earthworm Jim 2','','',null,null,null,array[''],'','SNES'),
('SNES164','Congo''s Caper','','Tatakae Genshijin 2: Rookie no Bōken',null,null,null,array[''],'','SNES'),
('SNES165','Umihara Kawase','','Umihara Kawase',null,null,null,array[''],'','SNES'),
('SNES166','Fighter''s History','','',null,null,null,array[''],'','SNES'),
('SNES167','Side Pocket','','',null,null,null,array[''],'','SNES');
select * from game
order by
case
when name_na is not null then name_na
else case
when name_eu is not null then name_eu
else name_jp
end
end;